# Site settings
baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Yuki Matsushita's Portfolio"
theme = "hugo-agency-theme"


[params]

	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Yuki Matsushita"
	description = "Your description"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "katsumeshi@gmail.com"


	# Navigation
	[params.navigation]
		brand = "Yuki Matsushita"
		portfolio = "Portfolio"
		services = "Skill"
		about = "Career"
		contact = "Contact"


	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		title = "I'm iOS Software Developer"
		subtitle = "Yuki Matsushita"
		buttonText = "Tell me more"


	# Services section
	[params.services]
		title = "Skill"
		subtitle = ""

	[[params.services.row]]

		[[params.services.row.list]]
			icon = "fa-laptop"
			title = "Objective-C"
			description = "I have experienced iOS Apps development for a total of 3 years.  Regarding Objective-C, I have experienced for over 2 years through some projects of former company. Those projects is used networking are Client-Server model. Not only iOS framework basic, I'm familiar with those methods also."
  #

		[[params.services.row.list]]
			icon = "fa-rocket"
			title = "Swift"
			description = "I have experience not only Objective-C, also Swift. I have started to use it on my own projects for about 1 year. Through those projects, I got also familiar with some library such as Alamofire, Realm, ReactiveCocoa, Quick(Testing framework). Recently, some of my own projects have already migrated to Swift2."
  #
		[[params.services.row.list]]
			icon = "fa-code"
			title = "Server-Side"
			description = "I'm especially familiar with Client-Side. Also, I have some Server-Side experience, PHP, Java, SQL, RDBMS, Jenkins, so on through previous projects. To improve my back-end skill, I continue to study through use of tutorial, reading tech books, so on."
 
	[[params.services.row]]
        [[params.services.row.list]]
			icon = "fa-gamepad"
			title = "Game Development"
			description = "I have game development experience using game engine also. I have used Unity, Cocos2d-x(trial), Cocos2d (without x), SpriteKit to make a game for a few months to a half year. Other than that, I have also experience Actionscript3 through making casual browser game for 1 year and a half."
 
         [[params.services.row.list]]
			icon = "fa-github-alt"
			title = "Tools and Team Work"
			description = "I got familiar with tools through the former company projects and my own projects.  Regarding source code management, I usually use Git/Github. For instance, In my former company, development process is we fix or develop based on issue that is made in Github or Project Management Tool using fix or feature branch, then send pull request to code review. After code review done, we merge it to development branch.  Other than that, I used Jenkins in my former company.  Personally, I use Vim, Zsh, Ansile, Vagrant, Docker,  so on to improve my work productivity.My favorite development tools are Xcode, Vim, Zsh."
  
    	[[params.services.row.list]]
			icon = "fa-fire"
			title = "Passion"
			description = "I love to programming. When I have spare time, I usually do learning or programming such as reading tech books, reading code, learning software architecture, beginning new programming language so on. IT field expansion is quickly, and developers should get a lot of new tech things.I think important of as a developer is attitude of learning various tech things every day."

	# Portfolio section
	[params.portfolio]
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "Portfolio"
		subtitle = ""

		[params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttonText = "Close project"


    # About section
	[params.about]
		title = "Career"
		subtitle = ""
		endpoint = "Be part<br>of my<br>story!"

		# The events will be listed from the top to the bottom.
		# All images are stored under 'static/img/about'.
		# Replace them with your own.
		[[params.about.events]]
			img = "1.jpg"
			date = "2004-2007"
			title = "Kobe Institute College of Computing. The Entertainmant Software Course"
			description = "I went to college for 3 years. <br> 1st year : learned knowledge of basic programming. <br> 2nd year : created a game as a project using VC++. <br> 3rd year : created bigger game as a graduation project using DirectX "

		[[params.about.events]]
			img = "2.jpg"
			date = "2007-2008"
			title = "M Technobrain Inc."
			description = "I participated in two projects during 1 year. One of the project that are developed by Java, I was charge of user registration function. the others project are I took part in developing of management system of a temporary employment agency using VB.Net."

		[[params.about.events]]
			img = "3.jpg"
			date = "2008-2012"
			title = "NEXON Co., Ltd"
			description = "The company is game publisher.  I was responsible for client-side of game creation that were used Action Script 3.  Last one and half year, I worked for as an infra engineer(on-premiss). The tasks are  monitoring , installing and maintaining the servers of MMO at IDC."

		[[params.about.events]]
			img = "4.jpg"
			date = "2012-2013"
			title = "KLab Inc."
			description = "The company is mobile game publisher. I was responsible for front-end(JavaScript) of operation of the browser game for a half a year. Then, I participated in startup of the iOS app game as a mobile software developer."

        [[params.about.events]]
			img = "5.jpg"
			date = "2013-2015"
			title = "KLab Cyscorpions Inc."
			description = "The company is located in the phillipines is overseas base subsidiary of KLab Inc. I transfered to the phillipines as an iOS Developer and client-side leader. I managed some projects as a client-side leader and made them improve their quality of skills, such as software designing, coding skills by conversation on Github or having some meetings.Aside from that, I participated in the game operation and development of CMS using PHP. In addition I took part in Unity, Cocos projects, also."

	# Footer section
	[params.footer]
		copyright = "Â© 2015 Yuki Matsushita."

        [[params.footer.social]]
			icon = "fa-github"
			link = "https://github.com/katsumeshi"

		[[params.footer.social]]
			icon = "fa-twitter"
			link = "https://twitter.com/__yukim"

		[[params.footer.social]]
			icon = "fa-facebook"
			link = "https://www.facebook.com/yuki.matsushita.39"

		[[params.footer.social]]
			icon = "fa-linkedin"
			link = "https://www.linkedin.com/profile/view?id=AAIAABj5CjYBI6DMaf9KjPcc7C59SveKjZLdj3Y&trk=nav_responsive_tab_profile_pic"

        [[params.footer.social]]
			icon = "fa-envelope-o"
			link = "mailto:katsumeshi@gmail.com"

	# Team section
	# [params.team]
	# 	title = "Our amazing team"
	# 	subtitle = "Lorem ipsum dolor sit amet consectetur."
	# 	description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde."
 #
	# 	# All team member's pictures are stored under 'static/img/team'.
	# 	# Replace them with your own too.
	# 	[[params.team.members]]
	# 		img = "1.jpg"
	# 		name = "Kay Garland"
	# 		position = "Lead Designer"
	# 		social = [
	# 			["fa-twitter", "#"],
	# 			["fa-facebook", "#"],
	# 			["fa-linkedin", "#"]
	# 		]
 #
	# 	[[params.team.members]]
	# 		img = "2.jpg"
	# 		name = "Larry Parker"
	# 		position = "Lead Marketer"
	# 		social = [
	# 			["fa-twitter", "#"],
	# 			["fa-facebook", "#"],
	# 			["fa-linkedin", "#"]
	# 		]
 #
	# 	[[params.team.members]]
	# 		img = "3.jpg"
	# 		name = "Diana Pertersen"
	# 		position = "Lead Developer"
	# 		social = [
	# 			["fa-twitter", "#"],
	# 			["fa-facebook", "#"],
	# 			["fa-linkedin", "#"]
	# 		]
 #
	# # Client section
	# # All the clients' logos are stored under 'static/img/logos'.
	# # Replace them with your clients's logos.
	# [[params.clients]]
	# 	logo = "envato.jpg"
	# 	link = "#"
 #
	# [[params.clients]]
	# 	logo = "designmodo.jpg"
	# 	link = "#"
 #
	# [[params.clients]]
	# 	logo = "themeforest.jpg"
	# 	link = "#"
 #
	# [[params.clients]]
	# 	logo = "creative-market.jpg"
	# 	link = "#"
 #
 #
	# Contact section
	# [params.contact]
	# 	title = "Contact us"
	# 	subtitle  = "Lorem ipsum dolor sit amet consectetur."
	# 	buttonText = "Send message"
 #
	# 	# 'warning' defines error messages for invalid inputs
	# 	[params.contact.form.name]
	# 		text = "Your Name *"
	# 		warning = "Please enter your name."
 #
	# 	[params.contact.form.email]
	# 		text = "Your Email *"
	# 		warning = "Please enter your email address."
 #
	# 	[params.contact.form.phone]
	# 		text = "Your Phone *"
	# 		warning = "Please enter your phone number."
 #
	# 	[params.contact.form.message]
	# 		text = "Your Message *"
	# 		warning = "Please enter a message."
 #


		# [[params.footer.quicklinks]]
		# 	text = "Privacy Policy"
		# 	link = "#"
  #
		# [[params.footer.quicklinks]]
		# 	text = "Terms of Use"
		# 	link = "#"
