# Site settings
baseurl = "https://yukim.xyz/"
languageCode = "en-us"
title = "Yuki Matsushita's Portfolio"
theme = "hugo-agency-theme"
googleAnalytics = "UA-32627465-9"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Yuki Matsushita"
	description = "Your description"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "katsumeshi@gmail.com"


	# Navigation
	[params.navigation]
		brand = "Yuki Matsushita"
		portfolio = "Portfolio"
		services = "Skill"
		team = "Leaning"
		about = "Career"


	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		title = "I am iOS Software Developer"
		subtitle = "Yuki Matsushita"
		buttonText = "Tell me more"


	# Services section
	[params.services]
		title = "Skill"
		subtitle = ""

	[[params.services.row]]

		[[params.services.row.list]]
			icon = "fa-laptop"
			title = "iOS Development"
			description = "I have experienced iOS App development for 3 years+. The detail is that I have developed apps using Objective-C for 2 years+ and using Swift for 1 year+. As I have developed the apps since iOS6, I have deep knowledge of iOS Development. For instance, I have solved the memory leak problems several times and Client-Server integration. I could boost to development quickly and accurately your projects."

		[[params.services.row.list]]
			icon = "fa-rocket"
			title = "Library experience"
			description = "I am also familiar with not only iOS SDK but also libraries of major third party such as AFNetworking, Alamofire, Realm, ReactiveCocoa, FMDB, Quick(Testing framework), etc. It could install and integrate smoothly into your projects."

		[[params.services.row.list]]
			icon = "fa-code"
			title = "Server-Side"
			description = "I am especially familiar with Client-Side. Also, I have some Server-Side experience such us LAMP, PHP, Java, SQL, RDBMS and Jenkins etc. To improve my back-end skill, I continue to study through use of tutorial, reading tech books, so on."
 
	[[params.services.row]]
        [[params.services.row.list]]
			icon = "fa-gamepad"
			title = "Game Development"
			description = "I have game development experiences using game engine, which have been Unity, Cocos2d-x(trial), Cocos2d (without x), SpriteKit for a few months to a half year, respectively. Other than that, I have also experience Actionscript3 through making casual browser game for 1 year and a half."
 
         [[params.services.row.list]]
			icon = "fa-github-alt"
			title = "Tools and Team Work"
			description = "I am familiar with tools.For source management, Git/Github, Bazzar and SVN. For Editor or IDE, Xcode, Vim, Android Studio, Eclipse, so on.For Project management, Backlog, Redmine, Trac, WBS.For installing infrastructure, Docker, Vagrant, Ansile, VBox, VMWare. For communication tool, Slack, Chatwork, IRC."
  
    	[[params.services.row.list]]
			icon = "fa-fire"
			title = "Attitude"
			description = "I have experienced Agile Development also through the projects. In addition, I could deal with the project flexibly and quickly. I have confidence to handle spontaneously any problem that I analyze and prioritise. Furthermore, I can work on and be familiar with willingly and quickly and flexibly any tasks which is required even it is not my field."

	# Portfolio section
	[params.portfolio]
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "Portfolio"
		subtitle = ""

		[params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttonText = "Close project"


    # About section
	[params.about]
		title = "Career"
		subtitle = ""
		endpoint = "Be part<br>of my<br>story!"

		# The events will be listed from the top to the bottom.
		# All images are stored under 'static/img/about'.
		# Replace them with your own.
		[[params.about.events]]
			img = "1.jpg"
			date = "2004-2007"
			title = "Kobe Institute College of Computing. The Entertainmant Software Course"
			description = "I went to college for 3 years. <br> 1st year : learned knowledge of basic programming. <br> 2nd year : created a game as a project using VC++. <br> 3rd year : created bigger game as a graduation project using DirectX "

		[[params.about.events]]
			img = "2.jpg"
			date = "2007-2008"
			title = "M Technobrain Inc."
			description = "I participated in two projects during 1 year. One of the project that are developed by Java, I was charge of user registration function. the others project are I took part in developing of management system of a temporary employment agency using VB.Net."

		[[params.about.events]]
			img = "3.jpg"
			date = "2008-2012"
			title = "NEXON Co., Ltd"
			description = "The company is game publisher.  I was responsible for client-side of game creation that were used Action Script 3.  Last one and half year, I worked for as an infra engineer(on-premiss). The tasks are  monitoring , installing and maintaining the servers of MMO at IDC."

		[[params.about.events]]
			img = "4.jpg"
			date = "2012-2013"
			title = "KLab Inc."
			description = "The company is mobile game publisher. I was responsible for front-end(JavaScript) of operation of the browser game for a half a year. Then, I participated in startup of the iOS app game as a mobile software developer."

        [[params.about.events]]
			img = "5.jpg"
			date = "2013-2015"
			title = "KLab Cyscorpions Inc."
			description = "The company is located in the phillipines is overseas base subsidiary of KLab Inc. I transfered to the phillipines as an iOS Developer and client-side leader. I managed some projects as a client-side leader and made them improve their quality of skills, such as software designing, coding skills by conversation on Github or having some meetings.Aside from that, I participated in the game operation and development of CMS using PHP. In addition I took part in Unity, Cocos projects, also."

	# Footer section
	[params.footer]
		copyright = "Â© 2015 Yuki Matsushita."

        [[params.footer.social]]
			icon = "fa-github"
			link = "https://github.com/katsumeshi"

		[[params.footer.social]]
			icon = "fa-twitter"
			link = "https://twitter.com/__yukim"

		[[params.footer.social]]
			icon = "fa-facebook"
			link = "https://www.facebook.com/yuki.matsushita.39"

		[[params.footer.social]]
			icon = "fa-linkedin"
			link = "https://www.linkedin.com/profile/view?id=AAIAABj5CjYBI6DMaf9KjPcc7C59SveKjZLdj3Y&trk=nav_responsive_tab_profile_pic"

        [[params.footer.social]]
			icon = "fa-envelope-o"
			link = "mailto:katsumeshi@gmail.com"

	# Team section
	[params.team]
		title = "Learning"
		subtitle = ""
		description = "Recently, My iOS learning is FRP(functional reactive programming) using [ReactiveCocoa](//github.com/ReactiveCocoa/ReactiveCocoa) and TDD(Test driven development) using [Quick](//github.com/Quick/Quick). I try to implement a app using these library, see ([Github source code : PhotoInfo](//github.com/katsumeshi/PhotoInfo)) <br><br> On the other hand, not only learning for iOS or client-side, I am also interested in back-end development and developing App of Android. Though I have some knowledge about back-end, I especially focus on learning Ruby, Ruby on rails recently .<br><br>This portfolio site is also part of learning, I created the site using [hugo](//gohugo.io/) which is static web site engine based on golang and  using [Docker](//www.docker.com/) and [Vagrant](//www.vagrantup.com/) for building local environment development." 
